cache_size_mb: 2048
keep_alive: 200
web_ui: disable
postgres:
  connection_string: postgresql://${REMOTE_COS_USER}:${REMOTE_COS_PASSWORD}@192.168.10.102:5432/caop
  default_srid: 3763
  auto_bounds: calc
  pool_size: 20
  auto_publish:
    from_schemas:
    - caop2025
  tables:
    cont_areas_administrativas:
      schema: CAOP2025
      table: cont_areas_administrativas
      srid: 3763
      geometry_column: geometria
      bounds:
      - -9.471329738514978
      - 36.95442849448416
      - -6.172036613788427
      - 42.137567479664185
      geometry_type: POLYGON
      properties:
        area_ha: numeric
        distrito_ilha: varchar
        dtmnfr: varchar
        freguesia: varchar
        id: int8
        municipio: varchar
        nuts1: varchar
        nuts2: varchar
        nuts3: varchar
        perimetro_km: int4
        tipo_area_administrativa: varchar
    cont_distritos:
      schema: CAOP2025
      table: cont_distritos
      srid: 3763
      geometry_column: geometria
      bounds:
      - -9.471329738514978
      - 36.95442849448416
      - -6.172036613788427
      - 42.137567479664185
      geometry_type: MULTIPOLYGON
      properties:
        area_ha: numeric
        distrito: varchar
        dt: text
        n_freguesias: numeric
        n_municipios: int8
        nuts1: varchar
        perimetro_km: int4
    cont_freguesias:
      schema: CAOP2025
      table: cont_freguesias
      srid: 3763
      geometry_column: geometria
      bounds:
      - -9.471329738514978
      - 36.95442849448416
      - -6.172036613788427
      - 42.137567479664185
      geometry_type: MULTIPOLYGON
      properties:
        area_ha: numeric
        designacao_simplificada: text
        distrito_ilha: varchar
        dtmnfr: varchar
        freguesia: varchar
        municipio: varchar
        nuts1: varchar
        nuts2: varchar
        nuts3: varchar
        perimetro_km: int4
    cont_municipios:
      schema: CAOP2025
      table: cont_municipios
      srid: 3763
      geometry_column: geometria
      bounds:
      - -9.471329738514978
      - 36.95442849448416
      - -6.172036613788427
      - 42.137567479664185
      geometry_type: MULTIPOLYGON
      properties:
        area_ha: numeric
        distrito_ilha: varchar
        dtmn: text
        municipio: varchar
        n_freguesias: int8
        nuts1: varchar
        nuts2: varchar
        nuts3: varchar
        perimetro_km: int4
    cont_nuts1:
      schema: CAOP2025
      table: cont_nuts1
      srid: 3763
      geometry_column: geometria
      bounds:
      - -9.471329738514978
      - 36.95442849448416
      - -6.172036613788427
      - 42.137567479664185
      geometry_type: MULTIPOLYGON
      properties:
        area_ha: numeric
        codigo: varchar
        n_freguesias: numeric
        n_municipios: numeric
        nuts1: varchar
        perimetro_km: int4
    cont_nuts2:
      schema: CAOP2025
      table: cont_nuts2
      srid: 3763
      geometry_column: geometria
      bounds:
      - -9.471329738514978
      - 36.95442849448416
      - -6.172036613788427
      - 42.137567479664185
      geometry_type: MULTIPOLYGON
      properties:
        area_ha: numeric
        codigo: varchar
        n_freguesias: numeric
        n_municipios: numeric
        nuts1: varchar
        nuts2: varchar
        perimetro_km: int4
    cont_nuts3:
      schema: CAOP2025
      table: cont_nuts3
      srid: 3763
      geometry_column: geometria
      bounds:
      - -9.471329738514978
      - 36.95442849448416
      - -6.172036613788427
      - 42.137567479664185
      geometry_type: MULTIPOLYGON
      properties:
        area_ha: numeric
        codigo: varchar
        id: int8
        n_freguesias: numeric
        n_municipios: int8
        nuts1: varchar
        nuts2: varchar
        nuts3: varchar
        perimetro_km: int4
    cont_troco:
      schema: base
      table: cont_troco
      srid: 3763
      geometry_column: geometria
      bounds:
      - -9.471329738514978
      - 36.95442849448416
      - -6.172036613788427
      - 42.137567479664185
      geometry_type: LINESTRING
      properties:
        ea_direita: varchar
        ea_esquerda: varchar
        estado_limite_admin: varchar
        identificador: uuid
        inicio_objecto: timestamp
        motivo: varchar
        nivel_limite_admin: varchar
        pais: varchar
        significado_linha: varchar
        troco_parente: uuid
        utilizador: varchar
  functions: {}
