#FROM postgis/postgis:12-3.4-alpine
FROM postgis/postgis:15-3.3-alpine
#FROM postgis/postgis:15-3.3

RUN mkdir -p /docker-entrypoint-initdb.d

ADD ./initDB_remote.sql /docker-entrypoint-initdb.d/initDB.sql

