apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  LOCAL_DATABASE_URL: "postgresql://postgres:postgres@postgis:5432/geodb"
  REMOTE_CAOP_PASSWORD: "caop_password"
  REMOTE_CAOP_URL: "postgresql://caop_user:caop_password@caop.host.db:5433/dgt_local"
  REMOTE_INSPIRE_PASSWORD: "inspire_password"
  REMOTE_INSPIRE_URL: "postgresql://inspire_user:inspire_password@inspire.host.db:5434/dgt_local"
