apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiles
  template:
    metadata:
      labels:
        app: tiles
    spec:
      containers:
      - name: martin
        image: ghcr.io/maplibre/martin
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: LOCAL_DATABASE_URL
        - name: WATCH_MODE
          value: "true"
        command:
        - martin
        - --auto-bounds
        - calc
        - --keep-alive
        - "200"
        - --pool-size
        - "20"
        - --default-srid
        - "4326"
