# =================================================================
#
# Authors: doublebyte1 <jo@byteroad.net>>
#
# Copyright (c) 2024 doublebyte
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

services:

  apache-httpd:
    build: ./apache-httpd/
    container_name: httpd
    depends_on:
      - pygeoapi
    volumes:   
      - ./apache-httpd/httpd-ssl-test.conf:/usr/local/apache2/conf/httpd.conf      
      - /etc/certs/tests_fullchain1.pem:/usr/local/apache2/conf/tests/fullchain1.pem  
      - /etc/certs/tests_privkey1.pem:/usr/local/apache2/conf/tests/privkey1.pem
      - ./apache-httpd/logs:/usr/local/apache2/logs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
    restart: on-failure

  pygeoapi:
    image: geopython/pygeoapi:latest
    container_name: pygeoapi
    expose:
      - "80"
    environment:
      PYGEOAPI_CONFIG: docker-config.yml
      PYGEOAPI_OPENAPI: example-openapi.yml
    env_file:
      - .env     # path to your .env file
    volumes:
      - ./pygeoapi/docker.config.yml:/pygeoapi/local.config.yml
      - ./data:/data
      - ./pygeoapi/templates:/templates # jinja templates
      - ./pygeoapi/Logo_DGT.png:/pygeoapi/pygeoapi/static/img/Logo_DGT.png # logo
      # - ./pygeoapi/default.css:/pygeoapi/pygeoapi/static/css/default.css # ribbon
    restart: on-failure
    links:
      - tiles
      - tiles_caop
      - tiles_inspire
    networks:
      - default
    depends_on:
      db_and_api_init:
        condition: service_completed_successfully
        restart: true

  tiles:
    image: ghcr.io/maplibre/martin
    restart: on-failure
    environment:
      - DATABASE_URL=${LOCAL_DATABASE_URL}
      # - RUST_LOG=debug
      - WATCH_MODE=true
    command: --auto-bounds calc --cache-size 2048 --keep-alive 200 --pool-size 20 --webui disable --default-srid 4326 --save-config /tmp/config.yml
    env_file:
      - .env
    depends_on:
      - postgis
    networks:
      - default
    healthcheck:
      test: ["NONE"]

  tiles_caop:
    image: ghcr.io/maplibre/martin
    restart: on-failure
    environment:
      - DATABASE_URL=${REMOTE_CAOP_URL}
      # - RUST_LOG=debug
      - WATCH_MODE=true
    command: --auto-bounds calc --cache-size 2048 --keep-alive 200 --pool-size 20 --webui disable --default-srid 4326 --save-config /tmp/config.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
    healthcheck:
      test: ["NONE"]

  tiles_inspire:
    image: ghcr.io/maplibre/martin
    restart: on-failure
    environment:
      - DATABASE_URL=${REMOTE_INSPIRE_URL}
      # - RUST_LOG=debug
      - WATCH_MODE=true
    command: --auto-bounds calc --cache-size 2048 --keep-alive 200 --pool-size 100 --webui disable --default-srid 4326 --save-config /tmp/config.yml
    # command: --config /config.yml
    # volumes:
    #   - ./martin/config-inspire.yml:/config.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
    healthcheck:
      test: ["NONE"]

  postgis:
    build: ./postgis/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env     # path to your .env file
    expose:
       - 5432
    container_name: postgis
    volumes:
       - ./postgis/data:/var/lib/postgresql/data
       - ./postgis/scripts:/tmp/
    networks:
      - default
      - bridge1
    restart: on-failure

  db_and_api_init:
    build: ./utils/
    container_name: db_and_api_init
    env_file:
      - .env     # path to your .env file
    volumes:
      - ./pygeoapi/docker.config.yml:/pygeoapi/docker.config.yml
      - ./data:/data
    depends_on:
      - postgis
    networks:
      - default

networks:
  default:
  bridge1:
