FROM docker.io/matomo:5.1.2
USER root

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      libzip-dev \
 && docker-php-ext-install pdo_mysql \
 && apt-get purge -y --auto-remove libzip-dev \
 && rm -rf /var/lib/apt/lists/*

USER www-data
RUN echo " proxy_uri_header = 1" >> /var/www/html/config/config.ini.php
