apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: env-config
    behavior: merge
    literals:
      - HOST_URL=http://localhost:8080
      - REMOTE_CAOP_HOST=host.minikube.internal
      - REMOTE_INSPIRE_HOST=host.minikube.internal

labels:
- pairs:
    environment: local
  includeSelectors: true
  includeTemplates: true
