server:
  bind:
    host: 0.0.0.0
    port: 80
  url: ${HOST_URL}
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
  - pt-PT
  - en-US
  cors: true
  pretty_print: true
  limits:
    default_items: 100
    max_items: 5000
    on_exceed: throttle
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap
      contributors</a>'
  templates:
    path: /templates
    static: /pygeoapi/pygeoapi/static
logging:
  level: DEBUG
  logfile: /tmp/pygeoapi.log
metadata:
  identification:
    title:
      pt: Serviço OGC API da DGT
      en: OGC API Service from DGT
    description:
      pt: Plataforma de publicação de dados abertos da DGT em OGC API
      en: Plattform for publishing Open Data from DGT in OGC API
    keywords:
      pt:
      - DGT
      - dados abertos
      - OGC API
      - api
      en:
      - DGT
      - OPEN DATA
      - OGC API
      - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://ogcapi.dgterritorio.gov.pt/
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Direção-Geral do Território
    url: https://www.dgterritorio.gov.pt/
  contact:
    name: DGT
    position: DGT
    address: Rua Artilharia Um, 107
    city: Lisboa
    stateorprovince: Administrative Area
    postalcode: 1099-052
    country: Portugal
    phone: (+351) 21 381 96 00
    fax: (+351) 21 381 96 00
    email: igeografica@dgterritorio.pt
    url: https://www.dgterritorio.gov.pt/
    hours: Seg-Sext 08:00-17:00
    instructions: Durante as horas de serviço.
    role: pointOfContact
resources:
  ortos-rgb:
    type: collection
    title: OrtoSat 30 cm - Portugal Continental - 2023 (Cor Verdadeira)
    description: 'A cobertura OrtoSat2023 é uma cobertura de ortoimagens obtidas a
      partir de imagens de satélite de muito grande resolução espacial adquirida durante
      o ano de 2023 sobre o território de Portugal continental. A cobertura é composta
      por um mosaico equalizado e ininterrupto de imagens de satélite ortorretificadas
      com uma resolução espacial de 30 cm. As imagens utilizadas na produção do mosaico
      foram obtidas da constelação de satélites Pleiades-Neo (3 & 4) durante o período
      de abril a outubro de 2023. Disponibilização em cor verdadeira: RGB: Vermelho,
      Verde e Azul.'
    keywords:
    - Cor verdadeira
    - Imagem de Satélite
    - Deteção Remota
    - Cartografia Oficial
    - '2023'
    - infoMapAccessService
    - SMOS
    - Ortoimagens
    - OrtoSat2023
    - Ortoimagem
    - Orto
    - Ortofoto
    - Ortofotos
    - Ortofotomapa
    - Ortofotomapas
    - OrtoSat
    - DGT
    links:
    - type: text/html
      rel: canonical
      title: information
      href: https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/b2a1ca02-779b-4189-b895-85d10fff610f
      hreflang: en-US
    extents:
      spatial:
        bbox:
        - -10.1934
        - 36.7643
        - -5.70954
        - 42.2796
      crs: http://www.opengis.net/def/crs/EPSG/0/4326
    temporal:
      begin: null
      end: null
    providers:
    - type: map
      name: WMSFacade
      data: https://ortos.dgterritorio.gov.pt/wms/ortosat2023
      options:
        layer: ortoSat2023-CorVerdadeira
        style: default
        version: 1.3.0
      format:
        name: png
        mimetype: image/png
  ortos-irg:
    type: collection
    title: OrtoSat 30 cm - Portugal Continental - 2023 (Falsa Cor)
    description: 'A cobertura OrtoSat2023 é uma cobertura de ortoimagens obtidas a
      partir de imagens de satélite de muito grande resolução espacial adquirida durante
      o ano de 2023 sobre o território de Portugal continental. A cobertura é composta
      por um mosaico equalizado e ininterrupto de imagens de satélite ortorretificadas
      com uma resolução espacial de 30 cm. As imagens utilizadas na produção do mosaico
      foram obtidas da constelação de satélites Pleiades-Neo (3 & 4) durante o período
      de abril a outubro de 2023. Disponibilização em false cor: RGB: Infravermelho
      Próximo, Vermelho e Verde.'
    keywords:
    - Falsa cor
    - Imagem de Satélite
    - Deteção Remota
    - Cartografia Oficial
    - '2023'
    - infoMapAccessService
    - SMOS
    - Ortoimagens
    - OrtoSat2023
    - Ortoimagem
    - Orto
    - Ortofoto
    - Ortofotos
    - Ortofotomapa
    - Ortofotomapas
    - OrtoSat
    - DGT
    links:
    - type: text/html
      rel: canonical
      title: information
      href: https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/b2a1ca02-779b-4189-b895-85d10fff610f
      hreflang: en-US
    extents:
      spatial:
        bbox:
        - -10.1934
        - 36.7643
        - -5.70954
        - 42.2796
      crs: http://www.opengis.net/def/crs/EPSG/0/4326
    temporal:
      begin: null
      end: null
    providers:
    - type: map
      name: WMSFacade
      data: https://ortos.dgterritorio.gov.pt/wms/ortosat2023
      options:
        layer: ortoSat2023-FalsaCor
        style: default
        version: 1.3.0
      format:
        name: png
        mimetype: image/png
  cadastro:
    description: Parcelas Cadastrais
    extents:
      spatial:
        bbox:
        - -9.51
        - 36.96
        - -6.19
        - 42.15
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: 2000-10-30T18:24:39Z
        end: 2007-10-30T08:57:29Z
    keywords:
    - prédio
    - conservação cadastral
    - INSPIRECORE
    - DL_72_2023
    - Cadastro Oficial
    - HVD
    - cadastro
    - cadastro predial
    - carta cadastral
    - prédios cadastrados
    - cadastro predial atualizado
    - Base de Dados Nacional de Cadastro Predial
    - BDNCP
    - Direção-geral do Território
    - DGT
    - Geoespaciais
    links:
    - href: https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/73282c48-7f23-435c-ba41-592a96470080
      hreflang: en-US
      rel: canonical
      title: data
      type: text/csv
    providers:
    - crs:
      - http://www.opengis.net/def/crs/OGC/1.3/CRS84
      - http://www.opengis.net/def/crs/EPSG/0/4326
      - http://www.opengis.net/def/crs/EPSG/0/3857
      - http://www.opengis.net/def/crs/EPSG/0/4258
      - http://www.opengis.net/def/crs/EPSG/0/3763
      data:
        dbname: ${REMOTE_INSPIRE_DB}
        host: ${REMOTE_INSPIRE_HOST}
        port: ${REMOTE_INSPIRE_PORT}
        user: ${REMOTE_INSPIRE_USER}
        password: ${REMOTE_INSPIRE_PASSWORD}
        search_path:
        - inspire
      geom_field: geometry
      id_field: id
      name: PostgreSQL
      storage_crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      table: mv_cadastralparcel_4326
      type: feature
    - data: http://tiles_inspire:3000/mv_cadastralparcel_4326/{z}/{x}/{y}?f=mvt
      format:
        mimetype: application/vnd.mapbox-vector-tile
        name: pbf
      name: MVT-proxy
      options:
        schemes:
        - WebMercatorQuad
        zoom:
          max: 15
          min: 0
      type: tile
    title: Cadastro Predial (Continente)
    type: collection
  crus:
    description: Carta do Regime de Uso do Solo
    extents:
      spatial:
        bbox:
        - -9.785164
        - 36.962833
        - -6.0
        - 42.104653
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: 2000-10-30T18:24:39Z
        end: 2007-10-30T08:57:29Z
    keywords:
    - Uso do Solo
    - Portugal
    - CRUS
    links:
    - href: https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/517c5023-04cc-47a4-99f7-bb32814dd62f
      hreflang: en-US
      rel: canonical
      title: data
      type: text/csv
    providers:
    - crs:
      - http://www.opengis.net/def/crs/OGC/1.3/CRS84
      - http://www.opengis.net/def/crs/EPSG/0/4326
      - http://www.opengis.net/def/crs/EPSG/0/3857
      - http://www.opengis.net/def/crs/EPSG/0/4258
      - http://www.opengis.net/def/crs/EPSG/0/3763
      data:
        dbname: geodb
        host: postgis
        user: ${POSTGRES_USER}
      geom_field: geometry
      id_field: objectid
      name: PostgreSQL
      search_path:
      - geostore
      - public
      storage_crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      table: crus
      type: feature
    - data: http://tiles:3000/crus/{z}/{x}/{y}?f=mvt
      format:
        mimetype: application/vnd.mapbox-vector-tile
        name: pbf
      name: MVT-proxy
      options:
        schemes:
        - WebMercatorQuad
        zoom:
          max: 15
          min: 0
      type: tile
    title: CRUS Portugal Continental
    type: collection